### ISSUE TITLE
Les types déclarés en typescript sont parfois incomplets

### ISSUE THREAD

**Issue by chrnin** [signaux-faibles/opensignauxfaibles#124]
Exemple repéré pour apdemande

le type est déclaré comme cela en TS:
```ts
type EntréeApDemande = {
  id_demande: string
  periode: { start: Date; end: Date }
  hta: number /* Nombre total d'heures autorisées */
  motif_recours_se: number /* Cause d'activité partielle */
}
```
En regardant dans la base il y a d'autres champs qui sont nécessaires pour l'affichage frontend:
```js
"apdemande" : {
   "f34dbfad1168e80503d9bf266d86a44c" : {
      "id_demande" : "blublublu",
      "effectif_entreprise" : 5234,
      "effectif" : 5234,
      "date_statut" : ISODate("2009-06-17T00:00:00.000Z"),
      "periode" : {
      "start" : ISODate("2009-05-04T00:00:00.000Z"),
      "end" : ISODate("2009-07-31T00:00:00.000Z")
   },
   "hta" : 341.0,
   "mta" : 1725062200028.0,
   "effectif_autorise" : 4,
   "motif_recours_se" : 1,
   "heure_consommee" : 339.0,
   "montant_consommee" : 1725062200028.0,
   "effectif_consomme" : 4
}
```

J'ai remarqué le même genre de chose pour APConso mais je n'ai pas fait le tour de tous les types.

**Comment by adrienjoly** [comment]
Bien vu !

C'était volontaire, en tout cas dans un premier temps. Plutot que de vouloir être exhaustifs, on suivait une démarche de typage au fil de l'eau, en fonction des props qui étaient rééllement utilisées dans la codebase JS/TS, afin de ne pas sur-complexifier la transition de JS à TS.

À voir si on veut tous les compléter ASAP, ou si on continue de faire ça à la demande.

**Comment by adrienjoly** [comment]
Je propose de fermer ce ticket => je l'ai reporté comme point d'action ("garantir la synchro entre les JSON Schema et les types TypeScript") dans #87.
