### ISSUE TITLE
Vérification des parsers d'import

### ISSUE THREAD

**Issue by JazzyPierrot** [signaux-faibles/opensignauxfaibles#167]
Suite à #164 

Il faudrait vérifier les spécifications suivantes pour les parsers d'import: 
- ~~Toute erreur fatale devrait immédiatement interrompre le script d'import~~
- [x] Toute erreur fatale devrait être reportée dans la collection "Journal" (ex: oubli de tracker.report dans certains cas)
- [x] Le parser ne doit pas pouvoir se terminer sans faire de rapport dans la collection journal
- [x] En présence d'un fichier filter, tous les parsers doivent se conformer au filtrage demandé. 
- [x] En absence d'un fichier filter, il s'agit sans doute d'un oubli => validation manuelle pour lancer l'import ? 
- [x] Harmoniser l'affichage des erreurs dans la console de l'API (aucune?  que les fatales ? toutes ?) => faire dans `import` comme dans `check`
 
On poura commencer par une simplification de la gestion des erreurs, bien trop complexe actuellement

**Comment by adrienjoly** [comment]
- [ ] Refactoriser les parseurs de manière à éviter la duplication mais surtout les divergences possible de logique, notamment au niveau de la gestion d'erreurs et du comptage de lignes.

**Comment by adrienjoly** [comment]
De mon côté, j'avais noté les [pistes suivantes](https://trello.com/c/tg85uKVN/164-industrialiser-limportation-de-donn%C3%A9es), suite à nos discussions, il y a ~15 jours:

- [x] [Quick win] erreurs `Cycle 3267: Pas de siret associé au compte 917000001210173128 à la période 2020-07-09 00:00:00 +0000 UTC` (venant du parseur Délai) devraient paraitre dans la catégorie `filter` plutot que dans `fatal` des documents de la collection `Journal`.
- [x] [Quick win] ajouter une propriété `batch` dans les documents de `journal`
- [x] [Quick win] script pour savoir s'il y a eu des erreurs d'importation ou pas. (`report` de `journal`)
- [x] mettre `goupy.py`, scripts de `stockage` et scripts de Pierre dans un depot, pour versionner.
- [ ] fluidifier le prétraitement et parsing des fichiers urssaf, si les problèmes de corruption apparaissent encore => a minima, informer en cas de presence de caractères non imprimables. note: il faut passer en utf8 avant d'utiliser `sed`. peut etre que golang pourrait faire ce traitement a la place de sed => pas besoin de convertir ?
- [ ] [charge mentale] automatiser la création du filtre => appeler `create_filter` automatiquement a partir du fichier `effectif` trouvé dans goup, prévenir s'il manque le filtre lors de l'appel à `prepare-import` et déterminer `date_fin_effectif` (a verifier si c'est pas deja fait dans `create_filter`: `getLastNotMissing()` ?).
- [ ] automatiser fichiers SIRENE: telecharger les derniere version de données diane (cf procédure), à savoir que les commandes de `wget` imposent à Pierre d'ouvrir sa connexion internet => est-ce qu'on pourrait faire recupérer ces fichiers par `goup` ? Note: ca prend plusieurs minutes a telecharger. `stockage` a besoin d'un serveur proxy depuis la machine hote pour acceder a internet.
- [ ] automatiser traitement sur Diane (génération du fichier excel `filter_to_diane.awk`: filtre --> filtre pour Diane, à partir d'un parametre à récuperer depuis l'interface web de diane, sans avoir à stripper les prefixes `0` => considerer les deux colonnes comme tu texte et non des nombres)
- [ ] Idée plus long terme: transformer `dbmongo` en CLI (au lieu d'une API), puis y intégrer prepare-import
- [ ] à réfléchir: réutiliser le meme filtre pour tous les sous-batch d'un meme batch
- [ ] [Vérification des parsers d'import · Issue #167 · signaux-faibles/opensignauxfaibles](https://github.com/signaux-faibles/opensignauxfaibles/issues/167)

**Comment by adrienjoly** [comment]
Je viens de fusionner un gros morceau: [fix(parsers): Itération de parsing pilotée par runParserWithSirenFilter()](https://github.com/signaux-faibles/opensignauxfaibles/pull/225)
