### ISSUE TITLE
Absence d'historique sur les données flux qui dépassent désormais le seuil de 10 salariés

### ISSUE THREAD

**Issue by adrienjoly** [signaux-faibles/opensignauxfaibles#200]
Steps:

- [x] identifier quels types de fichiers sont concernés => tous les fichiers qu'on recoit en flux (c.a.d. urssaf + diane) devraient nous etre envoyés plus régulierement en stock. 
- ~~demander à l'URSSAF qu'ils nous envoient un fichier stock à chaque début d'année (en plus des fichiers stock d'effectif qu'ils nous envoient deja chaque mois) => changer le périmètre (critère de filtrage des entreprises): se baser sur l'effectif de chaque établissement en début d'année . reformulation: dès qu'on met a jour le filtre, il faut qu'on réimporte toutes les données stock a jour dont on dispose + appliquer les ajouts des fichiers flux.~~
- ~~ou demander à l'URSSAF de changer ses requêtes pour inclure l'historique des entreprises/établissements qui dépassent désormais le seuil de 10 salariés, dans les fichiers flux. (=> ils nous fournissent des fichiers _hybrides_, ce serait l'idéal pour nous, car pas grand chose à changer)~~
- [ ] idem pour DIANE, à moins qu'on ne récupère ces données depuis une autre source

EDIT: Finalement, l'URSSAF va nous envoyer des fichiers stock/complets tous les 3 mois.

**Comment by adrienjoly** [comment]
Potentiellement lié à #205 ?

**Comment by adrienjoly** [comment]
Suite à discussion avec Pierre:
- ex: si on importe une entreprise vient de passer à 10 salariés (c.a.d. elle n'est plus sautée par le filtre, désormais) => le dernier fichier flux ne contiendra que très peu d'historique sur cette entreprise.

**Comment by adrienjoly** [comment]
@chrnin Peut-on considérer que le problème d'absence d'historique de données d'entreprises qui sont récemment entrées dans le périmètre est réglé par le fait que l'URSSAF va désormais nous envoyer des fichiers complets tous les 3 mois ?

Si tu confirmes, je vais fermer ce ticket.

**Comment by adrienjoly** [comment]
Christophe va re-importer tous les fichiers Diane avec le filtre du batch `2011`.

**Comment by adrienjoly** [comment]
@chrnin Au final, as-tu réimporté toutes les données Diane (fichiers stock), récemment ? Si oui, je suppose qu'on peut fermer ce ticket.

**Comment by chrnin** [comment]
Je confirme !
