### ISSUE TITLE
Out of memory sur un import de grande taille, pour un seul SIREN

### ISSUE THREAD

**Issue by chrnin** [signaux-faibles/opensignauxfaibles#210]
```
[...]
Reading csv line 111094403                                                                                                                             
Reading csv line 111098545                                                                                                                             
Reading csv line 111098910                                                                                                                             
Reading csv line 111102531                                                                                                                             
Reading csv line 111104276                                                                                                                             
Reading csv line 111106390                                                                                                                             
fatal error: runtime: out of memory            
```

Cela a eu lieu sur l'import du batch `2010_2` sur la base de données test2 (qui est une copie de la base de production… c'est plus rassurant pour bricoler)

Le batch est plutôt imposant car il y a des gros fichiers comme en atteste le nombre de lignes… En l'occurence je filtre tous les siren sauf un, et mon hypothèse est que la mémoire se remplit de messages concernant le filtrage.

**Comment by adrienjoly** [comment]
Après discussion avec Christophe, il se pourrait que ce soit le `cache` de `comptes` urssaf qui soit très volumineux en mémoire. => Vérifier que le filtre de SIRET/SIREN est bien appliqué sur ce cache, pour éviter de tout charger.

**Comment by adrienjoly** [comment]
@chrnin Quand tu dis _ je filtre tous les siren sauf un_, tu veux dire que tu whiteliste tous les SIREN sauf un, ou que tu exclue tous les SIREN sauf un ?

**Comment by chrnin** [comment]
Non je n'en whitelist qu'un, ils sont donc tous rejetés sauf un seul.

**Comment by adrienjoly** [comment]
Je viens de vérifier qu'aucun mapping n'est stocké pour les SIREN exclus par le Filtre, c'est prouvé par ce test: https://github.com/signaux-faibles/opensignauxfaibles/blob/944cb844f72e5d2c1d5df9dfdf83da4f6ec7b28c/dbmongo/lib/marshal/mapping_test.go#L101

=> Il me semble donc que l'hypothèse d'un trop grand nombre d'erreurs de filtrage stockées en mémoire soit plus plausible.
