### ISSUE TITLE
Compact plante lorsqu'il n'y a aucun débit

### ISSUE THREAD

**Issue by chrnin** [signaux-faibles/opensignauxfaibles#211]
Suite à mes expériences, j'en suis arrivé à tester le compactage avec aucun objet débit dans importedData mais des objets cotisation (voir base test2).

Mon hypothèse est que l'absence de débits crée une variable undefined qui est ensuite utilisée comme un objet.

```
# http --timeout=360 :3000/api/data/compact fromBatchKey="2010_2"
                                   
HTTP/1.1 500 Internal Server Error
Content-Length: 166
Content-Type: application/json; charset=utf-8
Date: Sun, 18 Oct 2020 21:59:19 GMT

"TypeError: can't convert undefined to object :\nforEachPopulatedProp@:5:5\nlistHashesToAddAndDelete@:11:5\ncompactBatch@:10:41\nreduce/<@:61:32\nreduce@:57:5\n"
```

**Comment by adrienjoly** [comment]
Merci pour ce rapport ! Je vais tenter de reproduire et corriger.

**Comment by adrienjoly** [comment]
Pour info, je ne parviens (pour l'instant) pas à reproduire de bug en exécutant le test unitaire suivant:

![image](https://user-images.githubusercontent.com/531781/96708641-cb7fb380-1399-11eb-9aac-57e49c542136.png)

**Comment by adrienjoly** [comment]
Je ne suis pas non plus parvenir à reproduire à retirant toutes les entrées `debit` de `test-api-compact.sh`.

**Comment by adrienjoly** [comment]
Vu le call stack:

- `f.compactBatch(currentBatch...` depuis `compact/reduce.ts:96`
- `f. listHashesToAddAndDelete(currentBatch...` depuis `compact/compactBatch.ts:25`
- `f.forEachPopulatedProp(compactDelete...` (avec `compactDelete` qui est sensé être un objet bien défini) depuis `compact/listHashesToAddAndDelete.ts:30`
- `Object.keys(obj)` (source probable de l'erreur) depuis `common/forEachPopulatedProp.ts:7`

=> Mon hypothèse est que il reste dans la base une entrée `delete` qui est non définie au lieu d'être un objet valide.

=> Piste: détecter et supprimer les entrées `delete` de `compact`, ex: dans `applyPatchesToBatch()`

**Comment by adrienjoly** [comment]
Erratum: voici l'appel qui cause l'erreur, dans la fonction `listHashesToAddAndDelete` de `jsFunctions.go`: 

```js
f.forEachPopulatedProp(currentBatch, (type) => {
```

**Comment by adrienjoly** [comment]
L'erreur `TypeError: can't convert undefined to object` a été reproduite: https://github.com/signaux-faibles/opensignauxfaibles/pull/216#issuecomment-714440850
