### ISSUE TITLE
Compact n'intègre pas certains tuples dans RawData

### ISSUE THREAD

**Issue by chrnin** [signaux-faibles/opensignauxfaibles#215]
Le cas se présente sur un établissement dont ces même tuples ont déjà été intégrés précédemment puis supprimés au mois de février.

La reproduction du bug est pour le moment assez longue puisqu'il faut importer tout le batch 2010_1 et le compacter (~13h de traitement) mais promis je fabriquerai un cas de test qui isole le bug ! ;)

**Comment by adrienjoly** [comment]
On vient de trouver le cas qui pose problème: quand un batch de cotisations est découpé en plusieurs documents dans `ImportedData`, seul les entrées cotisations du dernier document sont intégrées dans `RawData`.

=> je travaille sur un correctif: PR #217
