### ISSUE TITLE
[Discussion] Renommer certains champs des logs d'intégration

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/opensignauxfaibles#220]
Voilà un exemple de logs "résumé du parsing" (cf. #219 ) produits au 21 octobre:

```json
{
  "date":  1603239456.893,
  "event":[
    {
      "total":      111108091,
      "valid":      41741053,
      "filtered":      69367038,
      "error":      0,
      "headErrors":[],
      "headFatal":[],
      "batchKey":"2010_1",
      "report":"/2010_2/9a047825d8173684b69994428449302f: int\u00e9gration termin\u00e9e, 111108091 lignes trait\u00e9es, 0 erreures fatales, 0 rejets, 69367038 lignes filtr\u00e9es, 41741053 lignes valides",
      "headFilters":[
"Cycle 204: Pas de siret associ\u00e9 au compte 116000001439401120 \u00e0 la p\u00e9riode 2007-01-01 00:00:00 +0000 UTC"
      ]
    }
  ],
  "priority":"debug",
  "code":"debitParser"
}
```

et une proposition de renommage (et de rajout pour le compteur de lignes fatales) qui suivent je pense des bonnes pratiques de nommages en rendant notamment plus explicites les noms des champs.
- date ✅ 
- event ✅ 
  - total ➡️ **linesParsed**
  - valid ➡️ **linesValid**
  - filtered ➡️ **linesFiltered**
  - error ➡️ **linesRejected**
  - 🆕 **linesFatal** 🆕  (même si ce nombre doit par définition être 1 ou 0, c'est mieux de l'avoir explicitement par cohérence)
  - headErrors ➡️ **headRejected**
  - headFatal ✅ 
  - headFilters ➡️ **headFiltered**
  - batchKey ✅ 
  - report ➡️ **summary**
- priority ✅ 
- code ➡️ **parserCode** (sauf erreur, ce sont tous des parseurs?)

WDYT ?

**Comment by adrienjoly** [comment]
Ta proposition me parait très bien. Seul suggestion que j'ajouterais: employer `skipped` plutôt que `filtered`, si vous n'avez pas d'objection.
