### ISSUE TITLE
Rajouter paydex_nb_jours_last_3 and paydex_nb_jours_last_6

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/opensignauxfaibles#325]
Afin d'être le plus proche possible de ce qui nous a été présenté par Altares sur la donnée paydex. Il faudrait que le `reduce` calcule également les lags à 3 et 6 mois de la donnée.

On peut supprimer le lag a 1 mois (`paydex_nb_jours_last_1`)

**Comment by adrienjoly** [comment]
Fait dans PR #326.
