### ISSUE TITLE
bug: SIREN manquants

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/opensignauxfaibles#368]
## Problème
Le champs `siren` est parfois manquant dans `Features` alors même que le champs `siret` est bien renseigné.
En théorie, il devrait suffire de calculer le SIREN a partir des 9 premiers chiffres du SIRET.

## Exemples
Récupérés depuis notre client python :
<img width="506" alt="Screenshot 2021-05-25 at 11 01 55" src="https://user-images.githubusercontent.com/30295971/119500864-8de86c00-bd68-11eb-8962-12e079746e1d.png">

**Comment by raphaelventura** [comment]
Problème toujours en cours. Peut-être qu'on pourrait simplement retirer le siren de l'export, puisque cette information est de fait redondante.

**Comment by raphaelventura** [comment]
Géré désormais directement avec les fichiers partenaires source.
