### ISSUE TITLE
Mettre à jour la doc des variables avec l'unité

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/opensignauxfaibles#373]
Sur certaines variables, il serait utile de savoir si le montant est en euros ou (comme pour le CA récupéré via Diane) en kEUR 🤑 
cf.
https://github.com/signaux-faibles/opensignauxfaibles/blob/117a82607afe4fba7bb7f373a744d9a07993b044/js/reduce.algo2/docs/variables.json#L582

**Comment by raphaelventura** [comment]
En ce qui concerne la DS, la donnée est documentée directement sur le dépôt https://forge.dgfip.finances.rie.gouv.fr/dge/signaux-faibles/data-science-documentation
