### ISSUE TITLE
date de procédures collectives sur toutes les lignes

### ISSUE THREAD

**Issue by chrnin** [signaux-faibles/opensignauxfaibles#421]
il faut s'assurer que la date de procédure collective est présente y compris lorsqu'elle est dans le futur par rapport à la date période.
Cette information permettra de supprimer le champ `time_til_outcome`.

**Comment by raphaelventura** [comment]
Ceci n'est plus nécessaire depuis que nous récupérons la donnée URSSAF en direct et faisons la jointure côté lac
