### ISSUE TITLE
Mise en place de tests de validation de données au moment de l'import. 

### ISSUE THREAD

**Issue by JazzyPierrot** [signaux-faibles/opensignauxfaibles#87]
Contexte: 
En écrivant des tests pour délai, on a été tenté d'écrire un test de validation de cas limites (ou un dénominateur serait nul) qui normalement ne devrait pas arriver si les données sont valides. 

Proposition: 
* Définir un contrat pour chaque fonction d'algo2 concernant la validité des données en entrée
* Pour chaque fonction d'algo2, écrire une fonction de validation de données qui serait appelée au moment de l'import.
* Afin de garantir que les données historiques sont également valides, mettre un place une procédure de vérification de ces données qui serait exécutée à chaque fois que les contrats changent. 

Liste à compléter de règles à valider: 
* délai: 
  * `duree_delai` doit être strictement positif
  * `montant_echeancier` doit être strictement positif

**Comment by adrienjoly** [comment]
Nouvelles règles métier proposées par Pierre, lors d'une discussion sur Slack:

- si le parseur de delai/debit/apart détecte une valeur à 0 => on ne stocke pas le delai/debit/apart en base
- par contre, pour les autres dispositifs, on autorise les valeurs de 0
- dans tous les cas, on ne place pas de 0 comme valeur par défaut (si certaines valeurs manquent)
- concernant le calcul des ratios dans Diane: on maintient la règle qui dit que si le dénominateur d'un ratio est nul, on se contente de ne pas calculer ce ratio. => cette règle n'est pas une contrainte de validation de données Diane

**Comment by adrienjoly** [comment]
Priorités, suite à discussion avec Pierre:
- commencer par intégrer la validation dans `compact` (afin d'attraper les valeurs invalides qui auraient pu avoir été importées dans le passé)
- puis, si possible, l'intégrer également au processus d'`import`.

Types de règles de validation:
- regex, ex: pour détecter codes NAF anciens
- intervalle de valeur numérique, ex: `duree_delai` doit être strictement positif

Pour info, ces deux types de règles sont pris en charge par la [validation de mongodb](https://docs.mongodb.com/manual/core/schema-validation/) (superset de json schema).

**Comment by adrienjoly** [comment]
Réponse aux proposition de Pierre + status d'avancement:

> - Définir un contrat pour chaque fonction d'algo2 concernant la validité des données en entrée
> - Pour chaque fonction d'algo2, écrire une fonction de validation de données qui serait appelée au moment de l'import.

Sachant que (quasi) chaque fonction algo2 s'appuie majoritairement sur un seul type de données (ex: `Delai`, `Bdf`, ...), je propose qu'on écrive ces contrats+fonctions de validation pour chaque type de données, plutot que pour chaque fonction algo2. C'est ce que j'ai commencé à faire dans #143.

> - Afin de garantir que les données historiques sont également valides, mettre un place une procédure de vérification de ces données qui serait exécutée à chaque fois que les contrats changent.

J'ai ajouté un point d'entrée API `/api/data/validate` qui permet d'exécuter les règles de validations proposées ci-dessus, exprimées en JSON Schema, sur les documents de la collection `RawData`.

La prochaine étape que je préconise est d'intégrer ces règles au sein des collections `ImportedData` et `RawData`, de manière à ce que chaque document ajouté ou modifié soit systématiquement validé. Cela nous apporterait la garantie que tous les documents présents en DB sont valides, en permanence.

Par contre, reste à voir comment on gère les erreurs de validations qui pourraient survenir lors de ces manipulations.

**Comment by adrienjoly** [comment]
News: le point d'entrée `/api/data/validate` accepte désormais un paramètre `collection` permettant de spécifier la collection sur laquelle la validation doit être effectuée: `RawData` ou `ImportedData`.

Préconisation: penser à appeler cette API sur `ImportedData` après chaque importation de données, et avant l'appel au compactage, pour s'informer sur la présence éventuelle de documents incomplets/invalides et donner la possibilité de les retirer.

**Comment by adrienjoly** [comment]
Je mets cette tache en pause temporairement, au profit de #164. (jugé plus prioritaire)

**Comment by adrienjoly** [comment]
Avancement:

- [x] écriture de quelques règles de validation en JSON Schema
- [x] ajout d'APIs pour valider ces règles en bdd
- [x] documentation de ces APIs => https://github.com/signaux-faibles/documentation/blob/b93daa4d5be22bc69c2b16abc75e131fb457ab0d/processus-traitement-donnees.md#sp%C3%A9cificit%C3%A9s-du-compactage
- [ ] complétion des types en JSON Schema + règles associées
- [ ] validation systématique des documents en bdd

**Comment by adrienjoly** [comment]
@vviers il me semble que cette tache représente un des sujets qu'on discutait tout à l'heure.

Il se trouve que j'avais prévu de tacler cette semaine !

**Comment by adrienjoly** [comment]
Je vais activer la validation par MongoDB des données importées (lors de l'exécution de `sfdata import`).

Les règles de validation sont encore très lax. Il va donc falloir penser à les compléter.

Pour rappel, les règles de validation sont définies dans les fichiers `validation/*.schema.json` (un fichier par parseur), au format JSON Schema étendu de MongoDB (). Et, après chaque modification, il faut bien penser à exécuter `make test` pour regénérer les bundles envoyés à MongoDB et vérifier que les tests passent toujours.
